services:
  - type: web
    name: fsf-api
    runtime: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /api/health
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fsf-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: fsf-redis
          type: keyvalue
          property: connectionString  # URL redis://... interno

  # Redis (Render Key Value)
  - type: keyvalue
    name: fsf-redis
    plan: starter            # puoi anche usare 'free' se disponibile nel tuo workspace
    ipAllowList: []          # vuoto = solo rete interna di Render

databases:
  - name: fsf-postgres
    databaseName: fakesalefinder
    plan: basic-256mb        # piani validi: basic-256mb, basic-1gb, pro-8gb, ... (flessibili)
